version: '3.1'

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: myna_dev_postgres
    environment:
      POSTGRES_USER: myna
      POSTGRES_PASSWORD: devtest
      POSTGRES_DB: myna
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - './data/postgres/data:/var/lib/postgresql/data'
      - './data/psql:/opt/psql'
