name: Tests
on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache Docker images
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: docker-images-${{ runner.os }}
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: 'gradle'
    - name: run tests
      run: ./gradlew cleanTest test --info
    - name: check code style
      run: ./gradlew check --exclude-task test --info --rerun-tasks
