name: Tests
on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache Docker images
      uses: ScribeMD/docker-cache@0.3.7
      with:
        key: docker-images-${{ runner.os }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt-hotspot'
        cache: 'gradle'
    - name: run tests
      run: ./gradlew cleanTest test -i
